"""Dialect layer: canonical SQL in, engine-specific SQL out.

Everything here is pure text/value transformation with no driver dependency, so
the PostgreSQL rendering is unit-testable without a live server (see
tests/backend/test_p5_db.py). Two things differ between SQLite and PostgreSQL
and both are handled here:

  * **DDL types.** ``backend/db/sql/schema.sql`` is written in canonical tokens
    (TEXT / INTEGER / REAL / BOOLEAN / JSONDOC / IDENTITY) that each dialect
    expands to its own spelling.
  * **Parameter style.** Queries are written with named ``:param`` placeholders.
    sqlite3 takes those natively; psycopg wants ``%(param)s``.

Query *bodies* are deliberately dialect-neutral — ``ON CONFLICT ... DO UPDATE``
is supported by SQLite 3.24+ and PostgreSQL 9.5+, so there is one set of .sql
files rather than one per engine.
"""
from __future__ import annotations

import json
import re

SQLITE = "sqlite"
POSTGRES = "postgres"

#: Canonical type token -> (sqlite DDL, postgres DDL, python type name).
TYPES = {
    "TEXT":     ("TEXT", "TEXT", "str"),
    "INTEGER":  ("INTEGER", "INTEGER", "int"),
    "REAL":     ("REAL", "DOUBLE PRECISION", "float"),
    "BOOLEAN":  ("INTEGER", "BOOLEAN", "bool"),
    "JSONDOC":  ("TEXT", "JSONB", "Any"),
    "IDENTITY": ("INTEGER PRIMARY KEY AUTOINCREMENT",
                 "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "int"),
}

#: Order matters: longer tokens first so IDENTITY isn't clipped by a prefix.
_TYPE_RE = re.compile(r"\b(" + "|".join(sorted(TYPES, key=len, reverse=True)) + r")\b")


def python_type(canonical: str) -> str:
    return TYPES[canonical][2]


def render_ddl(schema_sql: str, dialect: str) -> str:
    """Expand canonical type tokens in schema.sql for `dialect`.

    Only tokens outside comments are touched; the header comment documents the
    canonical names and must survive verbatim.
    """
    idx = 0 if dialect == SQLITE else 1
    out = []
    for line in schema_sql.splitlines():
        code, sep, comment = line.partition("--")
        out.append(_TYPE_RE.sub(lambda m: TYPES[m.group(1)][idx], code) + sep + comment)
    return "\n".join(out)


#: `    name  TYPE rest-of-declaration` inside a CREATE TABLE body.
_COLUMN_RE = re.compile(
    r"^\s{2,}(?P<name>[a-z_][a-z0-9_]*)\s+(?P<decl>.+?),?\s*$", re.I)
_CREATE_TABLE_RE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?P<table>[a-z_][a-z0-9_]*)\s*\(",
    re.I)
#: Table-level constraints are not columns, whatever their indentation.
_NOT_A_COLUMN = re.compile(
    r"^(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT)\b", re.I)


def declared_columns(schema_sql: str):
    """``{table: {column: canonical declaration}}`` parsed from schema.sql.

    Used by ``Engine.migrate`` to add columns that a live table predates.
    Declarations keep their canonical type tokens, so the caller renders them
    for its own dialect.
    """
    tables, table, depth = {}, None, 0
    for raw in schema_sql.splitlines():
        line = raw.partition("--")[0].rstrip()
        if not line.strip():
            continue
        if table is None:
            m = _CREATE_TABLE_RE.search(line)
            if m:
                table, depth = m.group("table"), 1
                tables.setdefault(table, {})
            continue
        depth += line.count("(") - line.count(")")
        m = _COLUMN_RE.match(line)
        if m and not _NOT_A_COLUMN.match(m.group("name")):
            decl = m.group("decl").rstrip(",").strip()
            # A PRIMARY KEY / IDENTITY column cannot be added by ALTER TABLE
            # anyway, and by definition predates any later column.
            if not re.match(r"^(IDENTITY)\b", decl, re.I):
                tables[table][m.group("name")] = decl
        if depth <= 0:
            table = None
    return tables


def _split_statements(sql: str):
    """Split on semicolons that terminate a statement.

    Semicolons inside string literals and inside ``--`` comments are not
    terminators — prose in the schema header routinely contains both.
    """
    stmts, buf, quote, comment = [], [], None, False
    i = 0
    while i < len(sql):
        ch = sql[i]
        if comment:
            buf.append(ch)
            if ch == "\n":
                comment = False
        elif quote:
            buf.append(ch)
            if ch == quote:
                quote = None
        elif ch == "-" and sql[i:i + 2] == "--":
            comment = True
            buf.append(ch)
        elif ch in "'\"":
            quote = ch
            buf.append(ch)
        elif ch == ";":
            stmts.append("".join(buf))
            buf = []
        else:
            buf.append(ch)
        i += 1
    stmts.append("".join(buf))
    return [s for s in (s.strip() for s in stmts) if s and not _only_comments(s)]


def _only_comments(stmt: str) -> bool:
    """True when a fragment holds no SQL, just trailing comment lines."""
    return all(not line.strip() or line.strip().startswith("--")
               for line in stmt.splitlines())


def ddl_statements(schema_sql: str, dialect: str):
    """schema.sql rendered for `dialect` and split into executable statements."""
    return _split_statements(render_ddl(schema_sql, dialect))


# ``:name`` but not ``::cast`` and not inside a string literal.
_PARAM_RE = re.compile(r"(?<![:\w]):([a-z_][a-z0-9_]*)", re.IGNORECASE)


def _mask_literals(sql: str):
    """Replace quoted-string contents with placeholders so parameter scanning
    never fires inside a literal. Returns (masked_sql, restore)."""
    literals = []

    def take(m):
        literals.append(m.group(0))
        return "\x00%d\x00" % (len(literals) - 1)

    masked = re.sub(r"'(?:[^']|'')*'", take, sql)
    return masked, lambda s: re.sub(r"\x00(\d+)\x00",
                                    lambda m: literals[int(m.group(1))], s)


def param_names(sql: str):
    """Ordered, de-duplicated ``:param`` names appearing in `sql`."""
    masked, _ = _mask_literals(sql)
    seen, out = set(), []
    for name in _PARAM_RE.findall(masked):
        if name not in seen:
            seen.add(name)
            out.append(name)
    return out


def render_query(sql: str, dialect: str) -> str:
    """Rewrite named placeholders into the dialect's parameter style."""
    if dialect == SQLITE:
        return sql                      # sqlite3 speaks :name natively
    masked, restore = _mask_literals(sql)
    return restore(_PARAM_RE.sub(lambda m: "%%(%s)s" % m.group(1), masked))


# --------------------------------------------------------------------------
# Value codecs
#
# The generated bindings know each column's canonical type, so encoding is a
# lookup rather than isinstance guesswork. SQLite has no boolean or JSON type;
# PostgreSQL has both, and psycopg needs dicts wrapped before they reach JSONB.
# --------------------------------------------------------------------------

def encode(value, canonical: str, dialect: str):
    """Python value -> driver parameter."""
    if value is None:
        return None
    if canonical == "BOOLEAN":
        return bool(value) if dialect == POSTGRES else int(bool(value))
    if canonical == "JSONDOC":
        if dialect == SQLITE:
            return value if isinstance(value, str) else json.dumps(value)
        from psycopg.types.json import Jsonb      # imported lazily: optional dep
        return Jsonb(json.loads(value) if isinstance(value, str) else value)
    if canonical == "REAL" and isinstance(value, (int, float)):
        return float(value)
    if canonical == "TEXT" and not isinstance(value, str):
        return str(value)               # Path, int ids, ...
    return value


def decode(value, canonical: str):
    """Driver value -> Python value. Dialect-independent: SQLite hands back the
    ints and JSON strings it stored, PostgreSQL hands back bools and dicts, and
    both normalise to the same Python types here."""
    if value is None:
        return None
    if canonical == "BOOLEAN":
        return bool(value)
    if canonical == "JSONDOC":
        return json.loads(value) if isinstance(value, (str, bytes)) else value
    if canonical == "REAL":
        return float(value)
    if canonical == "INTEGER":
        return int(value)
    return value
