"""Row types for the catalog schema.

GENERATED by backend/db/codegen.py from backend/db/sql/. Do not edit by hand:
change the .sql files and re-run `python -m backend.db.codegen`.
"""

from __future__ import annotations

import dataclasses
from typing import Any  # noqa: F401

from .dialect import decode


@dataclasses.dataclass(frozen=True)
class Track:
    """One row of the `tracks` table."""

    id: str
    name: str
    artist: str
    genre: str
    license: str
    license_nd: bool
    license_sa: bool
    license_nc: bool
    mixable: bool
    native_bpm: float
    camelot: str
    duration_s: float
    audio_path: str
    analysis_json: Any
    segments_json: Any

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("artist", "TEXT"), ("genre", "TEXT"),
        ("license", "TEXT"), ("license_nd", "BOOLEAN"), ("license_sa", "BOOLEAN"),
        ("license_nc", "BOOLEAN"), ("mixable", "BOOLEAN"), ("native_bpm", "REAL"),
        ("camelot", "TEXT"), ("duration_s", "REAL"), ("audio_path", "TEXT"),
        ("analysis_json", "JSONDOC"), ("segments_json", "JSONDOC"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class Variant:
    """One row of the `variants` table."""

    track_id: str
    grid_bpm: int
    ratio: float
    path: str
    duration_s: float

    _FIELDS = (
        ("track_id", "TEXT"), ("grid_bpm", "INTEGER"), ("ratio", "REAL"),
        ("path", "TEXT"), ("duration_s", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class Latency:
    """One row of the `latency` table."""

    id: int
    stage: str
    track_id: str
    ms: float
    at: float

    _FIELDS = (
        ("id", "IDENTITY"), ("stage", "TEXT"), ("track_id", "TEXT"), ("ms", "REAL"),
        ("at", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class LatencySummaryRow:
    """Result row of the LatencySummary query."""

    stage: str
    n: int
    mean_ms: float
    min_ms: float
    max_ms: float

    _FIELDS = (
        ("stage", "TEXT"), ("n", "INTEGER"), ("mean_ms", "REAL"), ("min_ms", "REAL"),
        ("max_ms", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class ListTrackSummariesRow:
    """Result row of the ListTrackSummaries query."""

    id: str
    name: str
    artist: str
    genre: str
    license: str
    license_nd: bool
    license_sa: bool
    license_nc: bool
    mixable: bool
    native_bpm: float
    camelot: str
    duration_s: float

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("artist", "TEXT"), ("genre", "TEXT"),
        ("license", "TEXT"), ("license_nd", "BOOLEAN"), ("license_sa", "BOOLEAN"),
        ("license_nc", "BOOLEAN"), ("mixable", "BOOLEAN"), ("native_bpm", "REAL"),
        ("camelot", "TEXT"), ("duration_s", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


__all__ = ["Track", "Variant", "Latency", "LatencySummaryRow", "ListTrackSummariesRow"]
