"""Row types for the catalog schema.

GENERATED by backend/db/codegen.py from backend/db/sql/. Do not edit by hand:
change the .sql files and re-run `python -m backend.db.codegen`.
"""

from __future__ import annotations

import dataclasses
from typing import Any  # noqa: F401

from .dialect import decode


@dataclasses.dataclass(frozen=True)
class Track:
    """One row of the `tracks` table."""

    id: str
    name: str
    artist: str
    genre: str
    license: str
    license_nd: bool
    license_sa: bool
    license_nc: bool
    mixable: bool
    native_bpm: float
    camelot: str
    duration_s: float
    audio_key: str
    analysis_json: Any
    segments_json: Any
    status: str
    status_error: str
    source_url: str
    fetched_at: float
    analyzed_at: float
    ready_at: float
    outro_energy: float
    intro_energy: float
    deck_waveform: Any
    native_envelope: Any

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("artist", "TEXT"), ("genre", "TEXT"),
        ("license", "TEXT"), ("license_nd", "BOOLEAN"), ("license_sa", "BOOLEAN"),
        ("license_nc", "BOOLEAN"), ("mixable", "BOOLEAN"), ("native_bpm", "REAL"),
        ("camelot", "TEXT"), ("duration_s", "REAL"), ("audio_key", "TEXT"),
        ("analysis_json", "JSONDOC"), ("segments_json", "JSONDOC"), ("status", "TEXT"),
        ("status_error", "TEXT"), ("source_url", "TEXT"), ("fetched_at", "REAL"),
        ("analyzed_at", "REAL"), ("ready_at", "REAL"), ("outro_energy", "REAL"),
        ("intro_energy", "REAL"), ("deck_waveform", "JSONDOC"),
        ("native_envelope", "JSONDOC"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class Variant:
    """One row of the `variants` table."""

    track_id: str
    grid_bpm: int
    ratio: float
    object_key: str
    duration_s: float

    _FIELDS = (
        ("track_id", "TEXT"), ("grid_bpm", "INTEGER"), ("ratio", "REAL"),
        ("object_key", "TEXT"), ("duration_s", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class Latency:
    """One row of the `latency` table."""

    id: int
    stage: str
    track_id: str
    ms: float
    at: float

    _FIELDS = (
        ("id", "IDENTITY"), ("stage", "TEXT"), ("track_id", "TEXT"), ("ms", "REAL"),
        ("at", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class Mix:
    """One row of the `mixes` table."""

    id: str
    name: str
    head_id: str
    created_at: float
    updated_at: float

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("head_id", "TEXT"), ("created_at", "REAL"),
        ("updated_at", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class MixTrack:
    """One row of the `mix_tracks` table."""

    id: str
    mix_id: str
    track_id: str
    next_id: str
    delta_beats: int
    grid_bpm: int
    fade_s: float

    _FIELDS = (
        ("id", "TEXT"), ("mix_id", "TEXT"), ("track_id", "TEXT"), ("next_id", "TEXT"),
        ("delta_beats", "INTEGER"), ("grid_bpm", "INTEGER"), ("fade_s", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class LatencySummaryRow:
    """Result row of the LatencySummary query."""

    stage: str
    n: int
    mean_ms: float
    min_ms: float
    max_ms: float

    _FIELDS = (
        ("stage", "TEXT"), ("n", "INTEGER"), ("mean_ms", "REAL"), ("min_ms", "REAL"),
        ("max_ms", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class CountMixTracksByMixRow:
    """Result row of the CountMixTracksByMix query."""

    mix_id: str
    n: int

    _FIELDS = (
        ("mix_id", "TEXT"), ("n", "INTEGER"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class ListTrackSummariesRow:
    """Result row of the ListTrackSummaries query."""

    id: str
    name: str
    artist: str
    genre: str
    license: str
    license_nd: bool
    license_sa: bool
    license_nc: bool
    mixable: bool
    native_bpm: float
    camelot: str
    duration_s: float
    status: str
    outro_energy: float
    intro_energy: float

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("artist", "TEXT"), ("genre", "TEXT"),
        ("license", "TEXT"), ("license_nd", "BOOLEAN"), ("license_sa", "BOOLEAN"),
        ("license_nc", "BOOLEAN"), ("mixable", "BOOLEAN"), ("native_bpm", "REAL"),
        ("camelot", "TEXT"), ("duration_s", "REAL"), ("status", "TEXT"),
        ("outro_energy", "REAL"), ("intro_energy", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class ListDeckRowsRow:
    """Result row of the ListDeckRows query."""

    id: str
    name: str
    artist: str
    genre: str
    license: str
    license_nd: bool
    license_sa: bool
    license_nc: bool
    mixable: bool
    native_bpm: float
    camelot: str
    duration_s: float
    status: str
    outro_energy: float
    intro_energy: float
    deck_waveform: Any

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("artist", "TEXT"), ("genre", "TEXT"),
        ("license", "TEXT"), ("license_nd", "BOOLEAN"), ("license_sa", "BOOLEAN"),
        ("license_nc", "BOOLEAN"), ("mixable", "BOOLEAN"), ("native_bpm", "REAL"),
        ("camelot", "TEXT"), ("duration_s", "REAL"), ("status", "TEXT"),
        ("outro_energy", "REAL"), ("intro_energy", "REAL"),
        ("deck_waveform", "JSONDOC"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class GetTrackSummaryRow:
    """Result row of the GetTrackSummary query."""

    id: str
    name: str
    artist: str
    genre: str
    license: str
    license_nd: bool
    license_sa: bool
    license_nc: bool
    mixable: bool
    native_bpm: float
    camelot: str
    duration_s: float
    status: str
    outro_energy: float
    intro_energy: float

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("artist", "TEXT"), ("genre", "TEXT"),
        ("license", "TEXT"), ("license_nd", "BOOLEAN"), ("license_sa", "BOOLEAN"),
        ("license_nc", "BOOLEAN"), ("mixable", "BOOLEAN"), ("native_bpm", "REAL"),
        ("camelot", "TEXT"), ("duration_s", "REAL"), ("status", "TEXT"),
        ("outro_energy", "REAL"), ("intro_energy", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class ListTracksMissingNativeEnvelopeRow:
    """Result row of the ListTracksMissingNativeEnvelope query."""

    id: str

    _FIELDS = (
        ("id", "TEXT"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class ListTracksMissingDeckWaveformRow:
    """Result row of the ListTracksMissingDeckWaveform query."""

    id: str

    _FIELDS = (
        ("id", "TEXT"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class ListTrackStatusesRow:
    """Result row of the ListTrackStatuses query."""

    id: str
    name: str
    artist: str
    mixable: bool
    status: str
    status_error: str
    fetched_at: float
    analyzed_at: float
    ready_at: float

    _FIELDS = (
        ("id", "TEXT"), ("name", "TEXT"), ("artist", "TEXT"), ("mixable", "BOOLEAN"),
        ("status", "TEXT"), ("status_error", "TEXT"), ("fetched_at", "REAL"),
        ("analyzed_at", "REAL"), ("ready_at", "REAL"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


@dataclasses.dataclass(frozen=True)
class ListTracksMissingEnergiesRow:
    """Result row of the ListTracksMissingEnergies query."""

    id: str

    _FIELDS = (
        ("id", "TEXT"),
    )

    @classmethod
    def _from_row(cls, row):
        return cls(*(decode(row[i], t)
                     for i, (_, t) in enumerate(cls._FIELDS)))


__all__ = ["Track", "Variant", "Latency", "Mix", "MixTrack", "LatencySummaryRow", "CountMixTracksByMixRow", "ListTrackSummariesRow", "ListDeckRowsRow", "GetTrackSummaryRow", "ListTracksMissingNativeEnvelopeRow", "ListTracksMissingDeckWaveformRow", "ListTrackStatusesRow", "ListTracksMissingEnergiesRow"]
