"""Typed query bindings.

Each method runs one statement from backend/db/sql/queries/, with parameters
encoded and result rows decoded according to the canonical schema types.

GENERATED by backend/db/codegen.py from backend/db/sql/. Do not edit by hand:
change the .sql files and re-run `python -m backend.db.codegen`.
"""

from __future__ import annotations

from . import models
from .dialect import decode, encode, render_query


#: Canonical SQL, keyed by query name. Rendered per dialect on first use.
SQL = {
    "InsertLatency": """INSERT INTO latency (stage, track_id, ms, at)
VALUES (:stage, :track_id, :ms, :at)""",
    "LatencySummary": """SELECT stage,
       COUNT(*) AS n,
       AVG(ms)  AS mean_ms,
       MIN(ms)  AS min_ms,
       MAX(ms)  AS max_ms
FROM latency
GROUP BY stage
ORDER BY stage""",
    "GetTrack": """SELECT * FROM tracks WHERE id = :id""",
    "ListTracks": """SELECT * FROM tracks ORDER BY id""",
    "ListMixableTracks": """SELECT * FROM tracks WHERE mixable = :mixable ORDER BY id""",
    "ListTrackSummaries": """SELECT id, name, artist, genre, license,
       license_nd, license_sa, license_nc,
       mixable, native_bpm, camelot, duration_s
FROM tracks
ORDER BY id""",
    "CountTracks": """SELECT COUNT(*) AS n FROM tracks""",
    "GetTrackAnalysis": """SELECT analysis_json FROM tracks WHERE id = :id""",
    "GetTrackSegments": """SELECT segments_json FROM tracks WHERE id = :id""",
    "UpsertTrack": """INSERT INTO tracks (id, name, artist, genre, license, license_nd, license_sa,
                    license_nc, mixable, native_bpm, camelot, duration_s,
                    audio_path, analysis_json, segments_json)
VALUES (:id, :name, :artist, :genre, :license, :license_nd, :license_sa,
        :license_nc, :mixable, :native_bpm, :camelot, :duration_s,
        :audio_path, :analysis_json, :segments_json)
ON CONFLICT (id) DO UPDATE SET
    name          = EXCLUDED.name,
    artist        = EXCLUDED.artist,
    genre         = EXCLUDED.genre,
    license       = EXCLUDED.license,
    license_nd    = EXCLUDED.license_nd,
    license_sa    = EXCLUDED.license_sa,
    license_nc    = EXCLUDED.license_nc,
    mixable       = EXCLUDED.mixable,
    native_bpm    = EXCLUDED.native_bpm,
    camelot       = EXCLUDED.camelot,
    duration_s    = EXCLUDED.duration_s,
    audio_path    = EXCLUDED.audio_path,
    analysis_json = EXCLUDED.analysis_json,
    segments_json = EXCLUDED.segments_json""",
    "DeleteTrack": """DELETE FROM tracks WHERE id = :id""",
    "ListVariantsForTrack": """SELECT * FROM variants WHERE track_id = :track_id ORDER BY grid_bpm""",
    "ListAllVariants": """SELECT * FROM variants ORDER BY track_id, grid_bpm""",
    "UpsertVariant": """INSERT INTO variants (track_id, grid_bpm, ratio, path, duration_s)
VALUES (:track_id, :grid_bpm, :ratio, :path, :duration_s)
ON CONFLICT (track_id, grid_bpm) DO UPDATE SET
    ratio      = EXCLUDED.ratio,
    path       = EXCLUDED.path,
    duration_s = EXCLUDED.duration_s""",
    "DeleteVariantsForTrack": """DELETE FROM variants WHERE track_id = :track_id""",
}

_RENDERED = {}


def sql_for(dialect_name):
    """Every statement rendered for `dialect_name` (cached)."""
    if dialect_name not in _RENDERED:
        _RENDERED[dialect_name] = {
            name: render_query(text, dialect_name)
            for name, text in SQL.items()}
    return _RENDERED[dialect_name]


class Queries:
    """Statement executor bound to one connection."""

    def __init__(self, conn, dialect_name):
        self._conn = conn
        self._dialect = dialect_name
        self._sql = sql_for(dialect_name)

    def _execute(self, name, params):
        cur = self._conn.cursor()
        cur.execute(self._sql[name], params)
        return cur

    def insert_latency(self, stage, track_id, ms, at):
        """`InsertLatency` (:exec) -> None"""
        params = {
            "stage": encode(stage, "TEXT", self._dialect),
            "track_id": encode(track_id, "TEXT", self._dialect),
            "ms": encode(ms, "REAL", self._dialect),
            "at": encode(at, "REAL", self._dialect),
        }
        cur = self._execute("InsertLatency", params)
        cur.close()

    def latency_summary(self):
        """`LatencySummary` (:many) -> list[LatencySummaryRow]"""
        params = {}
        cur = self._execute("LatencySummary", params)
        rows = cur.fetchall()
        cur.close()
        return [models.LatencySummaryRow._from_row(r) for r in rows]

    def get_track(self, id):
        """`GetTrack` (:one) -> Track | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrack", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else models.Track._from_row(row)

    def list_tracks(self):
        """`ListTracks` (:many) -> list[Track]"""
        params = {}
        cur = self._execute("ListTracks", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Track._from_row(r) for r in rows]

    def list_mixable_tracks(self, mixable):
        """`ListMixableTracks` (:many) -> list[Track]"""
        params = {
            "mixable": encode(mixable, "BOOLEAN", self._dialect),
        }
        cur = self._execute("ListMixableTracks", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Track._from_row(r) for r in rows]

    def list_track_summaries(self):
        """`ListTrackSummaries` (:many) -> list[ListTrackSummariesRow]"""
        params = {}
        cur = self._execute("ListTrackSummaries", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListTrackSummariesRow._from_row(r) for r in rows]

    def count_tracks(self):
        """`CountTracks` (:scalar) -> int | None"""
        params = {}
        cur = self._execute("CountTracks", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "INTEGER")

    def get_track_analysis(self, id):
        """`GetTrackAnalysis` (:scalar) -> Any | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrackAnalysis", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "JSONDOC")

    def get_track_segments(self, id):
        """`GetTrackSegments` (:scalar) -> Any | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrackSegments", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "JSONDOC")

    def upsert_track(self, id, name, artist, genre, license, license_nd, license_sa, license_nc, mixable, native_bpm, camelot, duration_s, audio_path, analysis_json, segments_json):
        """`UpsertTrack` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
            "name": encode(name, "TEXT", self._dialect),
            "artist": encode(artist, "TEXT", self._dialect),
            "genre": encode(genre, "TEXT", self._dialect),
            "license": encode(license, "TEXT", self._dialect),
            "license_nd": encode(license_nd, "BOOLEAN", self._dialect),
            "license_sa": encode(license_sa, "BOOLEAN", self._dialect),
            "license_nc": encode(license_nc, "BOOLEAN", self._dialect),
            "mixable": encode(mixable, "BOOLEAN", self._dialect),
            "native_bpm": encode(native_bpm, "REAL", self._dialect),
            "camelot": encode(camelot, "TEXT", self._dialect),
            "duration_s": encode(duration_s, "REAL", self._dialect),
            "audio_path": encode(audio_path, "TEXT", self._dialect),
            "analysis_json": encode(analysis_json, "JSONDOC", self._dialect),
            "segments_json": encode(segments_json, "JSONDOC", self._dialect),
        }
        cur = self._execute("UpsertTrack", params)
        cur.close()

    def delete_track(self, id):
        """`DeleteTrack` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("DeleteTrack", params)
        cur.close()

    def list_variants_for_track(self, track_id):
        """`ListVariantsForTrack` (:many) -> list[Variant]"""
        params = {
            "track_id": encode(track_id, "TEXT", self._dialect),
        }
        cur = self._execute("ListVariantsForTrack", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Variant._from_row(r) for r in rows]

    def list_all_variants(self):
        """`ListAllVariants` (:many) -> list[Variant]"""
        params = {}
        cur = self._execute("ListAllVariants", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Variant._from_row(r) for r in rows]

    def upsert_variant(self, track_id, grid_bpm, ratio, path, duration_s):
        """`UpsertVariant` (:exec) -> None"""
        params = {
            "track_id": encode(track_id, "TEXT", self._dialect),
            "grid_bpm": encode(grid_bpm, "INTEGER", self._dialect),
            "ratio": encode(ratio, "REAL", self._dialect),
            "path": encode(path, "TEXT", self._dialect),
            "duration_s": encode(duration_s, "REAL", self._dialect),
        }
        cur = self._execute("UpsertVariant", params)
        cur.close()

    def delete_variants_for_track(self, track_id):
        """`DeleteVariantsForTrack` (:exec) -> None"""
        params = {
            "track_id": encode(track_id, "TEXT", self._dialect),
        }
        cur = self._execute("DeleteVariantsForTrack", params)
        cur.close()

__all__ = ["Queries", "SQL", "sql_for"]
