"""Typed query bindings.

Each method runs one statement from backend/db/sql/queries/, with parameters
encoded and result rows decoded according to the canonical schema types.

GENERATED by backend/db/codegen.py from backend/db/sql/. Do not edit by hand:
change the .sql files and re-run `python -m backend.db.codegen`.
"""

from __future__ import annotations

from . import models
from .dialect import decode, encode, render_query


#: Canonical SQL, keyed by query name. Rendered per dialect on first use.
SQL = {
    "InsertLatency": """INSERT INTO latency (stage, track_id, ms, at)
VALUES (:stage, :track_id, :ms, :at)""",
    "LatencySummary": """SELECT stage,
       COUNT(*) AS n,
       AVG(ms)  AS mean_ms,
       MIN(ms)  AS min_ms,
       MAX(ms)  AS max_ms
FROM latency
GROUP BY stage
ORDER BY stage""",
    "ListMixes": """SELECT * FROM mixes ORDER BY updated_at DESC""",
    "GetMix": """SELECT * FROM mixes WHERE id = :id""",
    "CountMixes": """SELECT COUNT(*) AS n FROM mixes""",
    "UpsertMix": """INSERT INTO mixes (id, name, head_id, created_at, updated_at)
VALUES (:id, :name, :head_id, :created_at, :updated_at)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    head_id    = EXCLUDED.head_id,
    updated_at = EXCLUDED.updated_at""",
    "RenameMix": """UPDATE mixes SET name = :name, updated_at = :updated_at WHERE id = :id""",
    "SetMixHead": """UPDATE mixes SET head_id = :head_id, updated_at = :updated_at WHERE id = :id""",
    "TouchMix": """UPDATE mixes SET updated_at = :updated_at WHERE id = :id""",
    "DeleteMix": """DELETE FROM mixes WHERE id = :id""",
    "ListMixTracks": """SELECT * FROM mix_tracks WHERE mix_id = :mix_id""",
    "CountMixTracksByMix": """SELECT mix_id, COUNT(*) AS n FROM mix_tracks GROUP BY mix_id""",
    "GetMixTrack": """SELECT * FROM mix_tracks WHERE id = :id""",
    "UpsertMixTrack": """INSERT INTO mix_tracks (id, mix_id, track_id, next_id, delta_beats, grid_bpm,
                        fade_s)
VALUES (:id, :mix_id, :track_id, :next_id, :delta_beats, :grid_bpm, :fade_s)
ON CONFLICT (id) DO UPDATE SET
    track_id    = EXCLUDED.track_id,
    next_id     = EXCLUDED.next_id,
    delta_beats = EXCLUDED.delta_beats,
    grid_bpm    = EXCLUDED.grid_bpm,
    fade_s      = EXCLUDED.fade_s""",
    "SetMixTrackDelta": """UPDATE mix_tracks SET delta_beats = :delta_beats WHERE id = :id""",
    "SetMixTrackNext": """UPDATE mix_tracks SET next_id = :next_id WHERE id = :id""",
    "DeleteMixTrack": """DELETE FROM mix_tracks WHERE id = :id""",
    "DeleteMixTracksForMix": """DELETE FROM mix_tracks WHERE mix_id = :mix_id""",
    "GetTrack": """SELECT * FROM tracks WHERE id = :id""",
    "ListTracks": """SELECT * FROM tracks ORDER BY id""",
    "ListMixableTracks": """SELECT * FROM tracks WHERE mixable = :mixable ORDER BY id""",
    "ListTrackSummaries": """SELECT id, name, artist, genre, license,
       license_nd, license_sa, license_nc,
       mixable, native_bpm, camelot, duration_s, status,
       outro_energy, intro_energy, popularity
FROM tracks
ORDER BY id""",
    "ListDeckRows": """SELECT id, name, artist, genre, license,
       license_nd, license_sa, license_nc,
       mixable, native_bpm, camelot, duration_s, status,
       outro_energy, intro_energy, deck_waveform, popularity
FROM tracks
ORDER BY id""",
    "GetTrackSummary": """SELECT id, name, artist, genre, license,
       license_nd, license_sa, license_nc,
       mixable, native_bpm, camelot, duration_s, status,
       outro_energy, intro_energy
FROM tracks WHERE id = :id""",
    "GetTrackNativeEnvelope": """SELECT native_envelope FROM tracks WHERE id = :id""",
    "SetTrackNativeEnvelope": """UPDATE tracks SET native_envelope = :native_envelope WHERE id = :id""",
    "ListTracksMissingNativeEnvelope": """SELECT id FROM tracks
WHERE analysis_json IS NOT NULL AND native_envelope IS NULL
ORDER BY id""",
    "SetTrackPopularity": """UPDATE tracks SET popularity = :popularity WHERE id = :id""",
    "ListTracksMissingPopularity": """SELECT id FROM tracks WHERE popularity IS NULL ORDER BY id""",
    "SetTrackDeckWaveform": """UPDATE tracks SET deck_waveform = :deck_waveform WHERE id = :id""",
    "ListTracksMissingDeckWaveform": """SELECT id FROM tracks
WHERE analysis_json IS NOT NULL AND deck_waveform IS NULL
ORDER BY id""",
    "CountTracks": """SELECT COUNT(*) AS n FROM tracks""",
    "GetTrackAnalysis": """SELECT analysis_json FROM tracks WHERE id = :id""",
    "GetTrackSegments": """SELECT segments_json FROM tracks WHERE id = :id""",
    "UpsertTrack": """INSERT INTO tracks (id, name, artist, genre, license, license_nd, license_sa,
                    license_nc, mixable, native_bpm, camelot, duration_s,
                    audio_key, analysis_json, segments_json,
                    status, status_error, source_url,
                    fetched_at, analyzed_at, ready_at)
VALUES (:id, :name, :artist, :genre, :license, :license_nd, :license_sa,
        :license_nc, :mixable, :native_bpm, :camelot, :duration_s,
        :audio_key, :analysis_json, :segments_json,
        :status, :status_error, :source_url,
        :fetched_at, :analyzed_at, :ready_at)
ON CONFLICT (id) DO UPDATE SET
    name          = EXCLUDED.name,
    artist        = EXCLUDED.artist,
    genre         = EXCLUDED.genre,
    license       = EXCLUDED.license,
    license_nd    = EXCLUDED.license_nd,
    license_sa    = EXCLUDED.license_sa,
    license_nc    = EXCLUDED.license_nc,
    mixable       = EXCLUDED.mixable,
    native_bpm    = COALESCE(EXCLUDED.native_bpm, tracks.native_bpm),
    camelot       = COALESCE(EXCLUDED.camelot, tracks.camelot),
    duration_s    = COALESCE(EXCLUDED.duration_s, tracks.duration_s),
    audio_key    = COALESCE(EXCLUDED.audio_key, tracks.audio_key),
    analysis_json = COALESCE(EXCLUDED.analysis_json, tracks.analysis_json),
    segments_json = COALESCE(EXCLUDED.segments_json, tracks.segments_json),
    status        = EXCLUDED.status,
    status_error  = EXCLUDED.status_error,
    source_url    = COALESCE(EXCLUDED.source_url, tracks.source_url),
    fetched_at    = COALESCE(EXCLUDED.fetched_at, tracks.fetched_at),
    analyzed_at   = COALESCE(EXCLUDED.analyzed_at, tracks.analyzed_at),
    ready_at      = COALESCE(EXCLUDED.ready_at, tracks.ready_at)""",
    "ClearTrackAnalysis": """UPDATE tracks SET analysis_json = NULL, segments_json = NULL,
                 outro_energy = NULL, intro_energy = NULL,
                 deck_waveform = NULL, native_envelope = NULL
WHERE id = :id""",
    "SetTrackStatus": """UPDATE tracks SET status = :status, status_error = NULL WHERE id = :id""",
    "MarkTrackFailed": """UPDATE tracks SET status_error = :status_error WHERE id = :id""",
    "StampTrackFetched": """UPDATE tracks SET fetched_at = :fetched_at WHERE id = :id""",
    "StampTrackAnalyzed": """UPDATE tracks SET analyzed_at = :analyzed_at WHERE id = :id""",
    "StampTrackReady": """UPDATE tracks SET ready_at = :ready_at WHERE id = :id""",
    "GetTrackStatus": """SELECT status FROM tracks WHERE id = :id""",
    "ListTrackStatuses": """SELECT id, name, artist, mixable, status, status_error,
       fetched_at, analyzed_at, ready_at
FROM tracks
ORDER BY id""",
    "ListTracksMissingEnergies": """SELECT id FROM tracks
WHERE analysis_json IS NOT NULL
  AND segments_json IS NOT NULL
  AND (outro_energy IS NULL OR intro_energy IS NULL)
ORDER BY id""",
    "SetTrackEnergies": """UPDATE tracks SET outro_energy = :outro_energy, intro_energy = :intro_energy
WHERE id = :id""",
    "DeleteTrack": """DELETE FROM tracks WHERE id = :id""",
    "ListVariantsForTrack": """SELECT * FROM variants WHERE track_id = :track_id ORDER BY grid_bpm""",
    "ListAllVariants": """SELECT * FROM variants ORDER BY track_id, grid_bpm""",
    "UpsertVariant": """INSERT INTO variants (track_id, grid_bpm, ratio, object_key, duration_s)
VALUES (:track_id, :grid_bpm, :ratio, :object_key, :duration_s)
ON CONFLICT (track_id, grid_bpm) DO UPDATE SET
    ratio      = EXCLUDED.ratio,
    object_key = EXCLUDED.object_key,
    duration_s = EXCLUDED.duration_s""",
    "DeleteVariantsForTrack": """DELETE FROM variants WHERE track_id = :track_id""",
}

_RENDERED = {}


def sql_for(dialect_name):
    """Every statement rendered for `dialect_name` (cached)."""
    if dialect_name not in _RENDERED:
        _RENDERED[dialect_name] = {
            name: render_query(text, dialect_name)
            for name, text in SQL.items()}
    return _RENDERED[dialect_name]


class Queries:
    """Statement executor bound to one connection."""

    def __init__(self, conn, dialect_name):
        self._conn = conn
        self._dialect = dialect_name
        self._sql = sql_for(dialect_name)

    def _execute(self, name, params):
        cur = self._conn.cursor()
        cur.execute(self._sql[name], params)
        return cur

    def insert_latency(self, stage, track_id, ms, at):
        """`InsertLatency` (:exec) -> None"""
        params = {
            "stage": encode(stage, "TEXT", self._dialect),
            "track_id": encode(track_id, "TEXT", self._dialect),
            "ms": encode(ms, "REAL", self._dialect),
            "at": encode(at, "REAL", self._dialect),
        }
        cur = self._execute("InsertLatency", params)
        cur.close()

    def latency_summary(self):
        """`LatencySummary` (:many) -> list[LatencySummaryRow]"""
        params = {}
        cur = self._execute("LatencySummary", params)
        rows = cur.fetchall()
        cur.close()
        return [models.LatencySummaryRow._from_row(r) for r in rows]

    def list_mixes(self):
        """`ListMixes` (:many) -> list[Mix]"""
        params = {}
        cur = self._execute("ListMixes", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Mix._from_row(r) for r in rows]

    def get_mix(self, id):
        """`GetMix` (:one) -> Mix | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetMix", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else models.Mix._from_row(row)

    def count_mixes(self):
        """`CountMixes` (:scalar) -> int | None"""
        params = {}
        cur = self._execute("CountMixes", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "INTEGER")

    def upsert_mix(self, id, name, head_id, created_at, updated_at):
        """`UpsertMix` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
            "name": encode(name, "TEXT", self._dialect),
            "head_id": encode(head_id, "TEXT", self._dialect),
            "created_at": encode(created_at, "REAL", self._dialect),
            "updated_at": encode(updated_at, "REAL", self._dialect),
        }
        cur = self._execute("UpsertMix", params)
        cur.close()

    def rename_mix(self, name, updated_at, id):
        """`RenameMix` (:exec) -> None"""
        params = {
            "name": encode(name, "TEXT", self._dialect),
            "updated_at": encode(updated_at, "REAL", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("RenameMix", params)
        cur.close()

    def set_mix_head(self, head_id, updated_at, id):
        """`SetMixHead` (:exec) -> None"""
        params = {
            "head_id": encode(head_id, "TEXT", self._dialect),
            "updated_at": encode(updated_at, "REAL", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetMixHead", params)
        cur.close()

    def touch_mix(self, updated_at, id):
        """`TouchMix` (:exec) -> None"""
        params = {
            "updated_at": encode(updated_at, "REAL", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("TouchMix", params)
        cur.close()

    def delete_mix(self, id):
        """`DeleteMix` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("DeleteMix", params)
        cur.close()

    def list_mix_tracks(self, mix_id):
        """`ListMixTracks` (:many) -> list[MixTrack]"""
        params = {
            "mix_id": encode(mix_id, "TEXT", self._dialect),
        }
        cur = self._execute("ListMixTracks", params)
        rows = cur.fetchall()
        cur.close()
        return [models.MixTrack._from_row(r) for r in rows]

    def count_mix_tracks_by_mix(self):
        """`CountMixTracksByMix` (:many) -> list[CountMixTracksByMixRow]"""
        params = {}
        cur = self._execute("CountMixTracksByMix", params)
        rows = cur.fetchall()
        cur.close()
        return [models.CountMixTracksByMixRow._from_row(r) for r in rows]

    def get_mix_track(self, id):
        """`GetMixTrack` (:one) -> MixTrack | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetMixTrack", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else models.MixTrack._from_row(row)

    def upsert_mix_track(self, id, mix_id, track_id, next_id, delta_beats, grid_bpm, fade_s):
        """`UpsertMixTrack` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
            "mix_id": encode(mix_id, "TEXT", self._dialect),
            "track_id": encode(track_id, "TEXT", self._dialect),
            "next_id": encode(next_id, "TEXT", self._dialect),
            "delta_beats": encode(delta_beats, "INTEGER", self._dialect),
            "grid_bpm": encode(grid_bpm, "INTEGER", self._dialect),
            "fade_s": encode(fade_s, "REAL", self._dialect),
        }
        cur = self._execute("UpsertMixTrack", params)
        cur.close()

    def set_mix_track_delta(self, delta_beats, id):
        """`SetMixTrackDelta` (:exec) -> None"""
        params = {
            "delta_beats": encode(delta_beats, "INTEGER", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetMixTrackDelta", params)
        cur.close()

    def set_mix_track_next(self, next_id, id):
        """`SetMixTrackNext` (:exec) -> None"""
        params = {
            "next_id": encode(next_id, "TEXT", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetMixTrackNext", params)
        cur.close()

    def delete_mix_track(self, id):
        """`DeleteMixTrack` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("DeleteMixTrack", params)
        cur.close()

    def delete_mix_tracks_for_mix(self, mix_id):
        """`DeleteMixTracksForMix` (:exec) -> None"""
        params = {
            "mix_id": encode(mix_id, "TEXT", self._dialect),
        }
        cur = self._execute("DeleteMixTracksForMix", params)
        cur.close()

    def get_track(self, id):
        """`GetTrack` (:one) -> Track | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrack", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else models.Track._from_row(row)

    def list_tracks(self):
        """`ListTracks` (:many) -> list[Track]"""
        params = {}
        cur = self._execute("ListTracks", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Track._from_row(r) for r in rows]

    def list_mixable_tracks(self, mixable):
        """`ListMixableTracks` (:many) -> list[Track]"""
        params = {
            "mixable": encode(mixable, "BOOLEAN", self._dialect),
        }
        cur = self._execute("ListMixableTracks", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Track._from_row(r) for r in rows]

    def list_track_summaries(self):
        """`ListTrackSummaries` (:many) -> list[ListTrackSummariesRow]"""
        params = {}
        cur = self._execute("ListTrackSummaries", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListTrackSummariesRow._from_row(r) for r in rows]

    def list_deck_rows(self):
        """`ListDeckRows` (:many) -> list[ListDeckRowsRow]"""
        params = {}
        cur = self._execute("ListDeckRows", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListDeckRowsRow._from_row(r) for r in rows]

    def get_track_summary(self, id):
        """`GetTrackSummary` (:one) -> GetTrackSummaryRow | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrackSummary", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else models.GetTrackSummaryRow._from_row(row)

    def get_track_native_envelope(self, id):
        """`GetTrackNativeEnvelope` (:scalar) -> Any | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrackNativeEnvelope", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "JSONDOC")

    def set_track_native_envelope(self, native_envelope, id):
        """`SetTrackNativeEnvelope` (:exec) -> None"""
        params = {
            "native_envelope": encode(native_envelope, "JSONDOC", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetTrackNativeEnvelope", params)
        cur.close()

    def list_tracks_missing_native_envelope(self):
        """`ListTracksMissingNativeEnvelope` (:many) -> list[ListTracksMissingNativeEnvelopeRow]"""
        params = {}
        cur = self._execute("ListTracksMissingNativeEnvelope", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListTracksMissingNativeEnvelopeRow._from_row(r) for r in rows]

    def set_track_popularity(self, popularity, id):
        """`SetTrackPopularity` (:exec) -> None"""
        params = {
            "popularity": encode(popularity, "INTEGER", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetTrackPopularity", params)
        cur.close()

    def list_tracks_missing_popularity(self):
        """`ListTracksMissingPopularity` (:many) -> list[ListTracksMissingPopularityRow]"""
        params = {}
        cur = self._execute("ListTracksMissingPopularity", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListTracksMissingPopularityRow._from_row(r) for r in rows]

    def set_track_deck_waveform(self, deck_waveform, id):
        """`SetTrackDeckWaveform` (:exec) -> None"""
        params = {
            "deck_waveform": encode(deck_waveform, "JSONDOC", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetTrackDeckWaveform", params)
        cur.close()

    def list_tracks_missing_deck_waveform(self):
        """`ListTracksMissingDeckWaveform` (:many) -> list[ListTracksMissingDeckWaveformRow]"""
        params = {}
        cur = self._execute("ListTracksMissingDeckWaveform", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListTracksMissingDeckWaveformRow._from_row(r) for r in rows]

    def count_tracks(self):
        """`CountTracks` (:scalar) -> int | None"""
        params = {}
        cur = self._execute("CountTracks", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "INTEGER")

    def get_track_analysis(self, id):
        """`GetTrackAnalysis` (:scalar) -> Any | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrackAnalysis", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "JSONDOC")

    def get_track_segments(self, id):
        """`GetTrackSegments` (:scalar) -> Any | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrackSegments", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "JSONDOC")

    def upsert_track(self, id, name, artist, genre, license, license_nd, license_sa, license_nc, mixable, native_bpm, camelot, duration_s, audio_key, analysis_json, segments_json, status, status_error, source_url, fetched_at, analyzed_at, ready_at):
        """`UpsertTrack` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
            "name": encode(name, "TEXT", self._dialect),
            "artist": encode(artist, "TEXT", self._dialect),
            "genre": encode(genre, "TEXT", self._dialect),
            "license": encode(license, "TEXT", self._dialect),
            "license_nd": encode(license_nd, "BOOLEAN", self._dialect),
            "license_sa": encode(license_sa, "BOOLEAN", self._dialect),
            "license_nc": encode(license_nc, "BOOLEAN", self._dialect),
            "mixable": encode(mixable, "BOOLEAN", self._dialect),
            "native_bpm": encode(native_bpm, "REAL", self._dialect),
            "camelot": encode(camelot, "TEXT", self._dialect),
            "duration_s": encode(duration_s, "REAL", self._dialect),
            "audio_key": encode(audio_key, "TEXT", self._dialect),
            "analysis_json": encode(analysis_json, "JSONDOC", self._dialect),
            "segments_json": encode(segments_json, "JSONDOC", self._dialect),
            "status": encode(status, "TEXT", self._dialect),
            "status_error": encode(status_error, "TEXT", self._dialect),
            "source_url": encode(source_url, "TEXT", self._dialect),
            "fetched_at": encode(fetched_at, "REAL", self._dialect),
            "analyzed_at": encode(analyzed_at, "REAL", self._dialect),
            "ready_at": encode(ready_at, "REAL", self._dialect),
        }
        cur = self._execute("UpsertTrack", params)
        cur.close()

    def clear_track_analysis(self, id):
        """`ClearTrackAnalysis` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("ClearTrackAnalysis", params)
        cur.close()

    def set_track_status(self, status, id):
        """`SetTrackStatus` (:exec) -> None"""
        params = {
            "status": encode(status, "TEXT", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetTrackStatus", params)
        cur.close()

    def mark_track_failed(self, status_error, id):
        """`MarkTrackFailed` (:exec) -> None"""
        params = {
            "status_error": encode(status_error, "TEXT", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("MarkTrackFailed", params)
        cur.close()

    def stamp_track_fetched(self, fetched_at, id):
        """`StampTrackFetched` (:exec) -> None"""
        params = {
            "fetched_at": encode(fetched_at, "REAL", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("StampTrackFetched", params)
        cur.close()

    def stamp_track_analyzed(self, analyzed_at, id):
        """`StampTrackAnalyzed` (:exec) -> None"""
        params = {
            "analyzed_at": encode(analyzed_at, "REAL", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("StampTrackAnalyzed", params)
        cur.close()

    def stamp_track_ready(self, ready_at, id):
        """`StampTrackReady` (:exec) -> None"""
        params = {
            "ready_at": encode(ready_at, "REAL", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("StampTrackReady", params)
        cur.close()

    def get_track_status(self, id):
        """`GetTrackStatus` (:scalar) -> str | None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("GetTrackStatus", params)
        row = cur.fetchone()
        cur.close()
        return None if row is None else decode(row[0], "TEXT")

    def list_track_statuses(self):
        """`ListTrackStatuses` (:many) -> list[ListTrackStatusesRow]"""
        params = {}
        cur = self._execute("ListTrackStatuses", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListTrackStatusesRow._from_row(r) for r in rows]

    def list_tracks_missing_energies(self):
        """`ListTracksMissingEnergies` (:many) -> list[ListTracksMissingEnergiesRow]"""
        params = {}
        cur = self._execute("ListTracksMissingEnergies", params)
        rows = cur.fetchall()
        cur.close()
        return [models.ListTracksMissingEnergiesRow._from_row(r) for r in rows]

    def set_track_energies(self, outro_energy, intro_energy, id):
        """`SetTrackEnergies` (:exec) -> None"""
        params = {
            "outro_energy": encode(outro_energy, "REAL", self._dialect),
            "intro_energy": encode(intro_energy, "REAL", self._dialect),
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("SetTrackEnergies", params)
        cur.close()

    def delete_track(self, id):
        """`DeleteTrack` (:exec) -> None"""
        params = {
            "id": encode(id, "TEXT", self._dialect),
        }
        cur = self._execute("DeleteTrack", params)
        cur.close()

    def list_variants_for_track(self, track_id):
        """`ListVariantsForTrack` (:many) -> list[Variant]"""
        params = {
            "track_id": encode(track_id, "TEXT", self._dialect),
        }
        cur = self._execute("ListVariantsForTrack", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Variant._from_row(r) for r in rows]

    def list_all_variants(self):
        """`ListAllVariants` (:many) -> list[Variant]"""
        params = {}
        cur = self._execute("ListAllVariants", params)
        rows = cur.fetchall()
        cur.close()
        return [models.Variant._from_row(r) for r in rows]

    def upsert_variant(self, track_id, grid_bpm, ratio, object_key, duration_s):
        """`UpsertVariant` (:exec) -> None"""
        params = {
            "track_id": encode(track_id, "TEXT", self._dialect),
            "grid_bpm": encode(grid_bpm, "INTEGER", self._dialect),
            "ratio": encode(ratio, "REAL", self._dialect),
            "object_key": encode(object_key, "TEXT", self._dialect),
            "duration_s": encode(duration_s, "REAL", self._dialect),
        }
        cur = self._execute("UpsertVariant", params)
        cur.close()

    def delete_variants_for_track(self, track_id):
        """`DeleteVariantsForTrack` (:exec) -> None"""
        params = {
            "track_id": encode(track_id, "TEXT", self._dialect),
        }
        cur = self._execute("DeleteVariantsForTrack", params)
        cur.close()

__all__ = ["Queries", "SQL", "sql_for"]
