"""Database layer — dialect rendering, generated bindings, concurrency.

The PostgreSQL half is exercised through the dialect layer rather than a live
server: rendering is pure text transformation, so the SQL that would be sent to
Supabase is asserted here without needing psycopg installed. Behaviour that
needs a real connection (pool checkout, MVCC) is not covered by this suite.
"""
import shutil
import sqlite3
import tempfile
import threading
import unittest
from pathlib import Path

from fixture import get_fixture, read

from backend.db import Database, DatabaseError, Queries, Track
from backend.db import codegen, dialect, engine as engine_mod
from backend.db.engine import SQLiteEngine, uses_transaction_pooler


class TestCodegen(unittest.TestCase):
    """The committed bindings must match the .sql sources."""

    def test_generated_files_are_not_stale(self):
        self.assertEqual(
            codegen.main(["--check"]), 0,
            "backend/db/models.py or queries.py is out of date — "
            "run: python -m backend.db.codegen")

    def test_every_query_is_bound_to_a_method(self):
        _, queries = codegen.load()
        self.assertTrue(queries)
        for q in queries:
            method = codegen._snake(q["name"])
            self.assertTrue(hasattr(Queries, method),
                            f"{q['name']} has no Queries.{method}")

    def test_schema_columns_become_model_fields(self):
        tables, _ = codegen.load()
        self.assertEqual([c for c, _ in tables["tracks"]],
                         [f.name for f in Track.__dataclass_fields__.values()])

    def test_unknown_column_type_is_rejected(self):
        with self.assertRaises(codegen.CodegenError):
            codegen.parse_schema("CREATE TABLE t (\n  a VARCHAR(20)\n);")

    def test_parameter_not_matching_a_column_is_rejected(self):
        tables = {"tracks": [("id", "TEXT")]}
        query = {"name": "Q", "kind": ":one", "sql": "SELECT * FROM tracks WHERE id = :nope",
                 "source": "x.sql", "columns": None}
        with self.assertRaises(codegen.CodegenError) as cm:
            codegen.infer_param_types(query, tables)
        self.assertIn("no column of that name", str(cm.exception))

    def test_explicit_select_list_requires_a_columns_annotation(self):
        tables = {"tracks": [("id", "TEXT")]}
        query = {"name": "Q", "kind": ":many", "sql": "SELECT id FROM tracks",
                 "source": "x.sql", "columns": None}
        with self.assertRaises(codegen.CodegenError) as cm:
            codegen.infer_result(query, tables)
        self.assertIn("columns", str(cm.exception))


class TestDialect(unittest.TestCase):
    """One set of .sql files has to render correctly for both engines."""

    def test_sqlite_keeps_named_placeholders(self):
        sql = "SELECT * FROM tracks WHERE id = :id"
        self.assertEqual(dialect.render_query(sql, dialect.SQLITE), sql)

    def test_postgres_uses_pyformat_placeholders(self):
        rendered = dialect.render_query(
            "SELECT * FROM tracks WHERE id = :id AND genre = :genre",
            dialect.POSTGRES)
        self.assertIn("%(id)s", rendered)
        self.assertIn("%(genre)s", rendered)
        self.assertNotIn(":id", rendered)

    def test_placeholders_inside_string_literals_are_left_alone(self):
        sql = "SELECT ':not_a_param' FROM tracks WHERE id = :id"
        self.assertEqual(dialect.param_names(sql), ["id"])
        rendered = dialect.render_query(sql, dialect.POSTGRES)
        self.assertIn("':not_a_param'", rendered)
        self.assertIn("%(id)s", rendered)

    def test_casts_are_not_read_as_parameters(self):
        self.assertEqual(dialect.param_names("SELECT x::text FROM t"), [])

    def test_ddl_types_differ_per_engine(self):
        schema = engine_mod.schema_sql()
        sqlite_ddl = dialect.render_ddl(schema, dialect.SQLITE)
        pg_ddl = dialect.render_ddl(schema, dialect.POSTGRES)
        def declaration(ddl, column):
            line = next(ln for ln in ddl.splitlines()
                        if ln.strip().startswith(column + " "))
            return " ".join(line.split()).rstrip(",")

        self.assertEqual(declaration(sqlite_ddl, "analysis_json"),
                         "analysis_json TEXT")
        self.assertEqual(declaration(pg_ddl, "analysis_json"),
                         "analysis_json JSONB")
        self.assertEqual(declaration(sqlite_ddl, "license_nd"),
                         "license_nd INTEGER NOT NULL")
        self.assertEqual(declaration(pg_ddl, "license_nd"),
                         "license_nd BOOLEAN NOT NULL")
        self.assertEqual(declaration(sqlite_ddl, "native_bpm"), "native_bpm REAL")
        self.assertEqual(declaration(pg_ddl, "native_bpm"),
                         "native_bpm DOUBLE PRECISION")
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", pg_ddl)
        self.assertIn("AUTOINCREMENT", sqlite_ddl)

    def test_semicolons_in_comments_do_not_split_statements(self):
        statements = dialect.ddl_statements(engine_mod.schema_sql(), dialect.SQLITE)
        self.assertEqual(sum(1 for s in statements if "CREATE TABLE" in s), 3)
        self.assertEqual(sum(1 for s in statements if "CREATE INDEX" in s), 2)

    def test_both_dialects_produce_executable_ddl_for_sqlite(self):
        """Sanity check that the canonical schema really is valid SQL."""
        con = sqlite3.connect(":memory:")
        for stmt in dialect.ddl_statements(engine_mod.schema_sql(), dialect.SQLITE):
            con.execute(stmt)
        names = {r[0] for r in con.execute(
            "SELECT name FROM sqlite_master WHERE type='table'")}
        self.assertTrue({"tracks", "variants", "latency"} <= names)
        con.close()

    def test_boolean_and_json_round_trip(self):
        for value in (True, False):
            self.assertIs(
                dialect.decode(dialect.encode(value, "BOOLEAN", dialect.SQLITE),
                               "BOOLEAN"), value)
        doc = {"bpm": 124.0, "beat_grid": [0.0, 0.48]}
        self.assertEqual(
            dialect.decode(dialect.encode(doc, "JSONDOC", dialect.SQLITE), "JSONDOC"),
            doc)

    def test_sqlite_stores_booleans_as_integers(self):
        self.assertEqual(dialect.encode(True, "BOOLEAN", dialect.SQLITE), 1)
        self.assertIs(dialect.encode(True, "BOOLEAN", dialect.POSTGRES), True)

    def test_postgres_jsonb_decodes_from_a_dict(self):
        """psycopg hands back a dict for JSONB; sqlite3 hands back a string.
        Both have to arrive at the same Python value."""
        doc = {"a": 1}
        self.assertEqual(dialect.decode(doc, "JSONDOC"), doc)
        self.assertEqual(dialect.decode('{"a": 1}', "JSONDOC"), doc)


class TestUrls(unittest.TestCase):
    def test_relative_and_absolute_sqlite_paths(self):
        self.assertEqual(engine_mod.engine_from_url("sqlite:///rel.db").path, "rel.db")
        self.assertEqual(engine_mod.engine_from_url("sqlite:////tmp/abs.db").path,
                         "/tmp/abs.db")

    def test_unsupported_scheme_is_rejected(self):
        with self.assertRaises(DatabaseError):
            engine_mod.engine_from_url("mysql://localhost/db")

    def test_in_memory_sqlite_is_rejected(self):
        with self.assertRaises(DatabaseError) as cm:
            engine_mod.engine_from_url("sqlite:///:memory:")
        self.assertIn("per-thread", str(cm.exception))

    def test_supabase_pooler_urls_are_recognised(self):
        self.assertTrue(uses_transaction_pooler(
            "postgresql://u:p@aws-0-eu-west-1.pooler.supabase.com:6543/postgres"))
        self.assertFalse(uses_transaction_pooler(
            "postgresql://u:p@db.abcdef.supabase.co:5432/postgres"))


class TestScopes(unittest.TestCase):
    """Transaction scoping, nesting and rollback."""

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="djdb_"))
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.database = Database.from_url(
            "sqlite:///" + str(self.tmp / "t.sqlite3")).migrate()
        self.addCleanup(self.database.dispose)

    def _count(self):
        with self.database.reading() as q:
            return len(q.latency_summary())

    def test_write_scope_commits(self):
        with self.database.writing() as q:
            q.insert_latency(stage="s", track_id=None, ms=1.0, at=0.0)
        self.assertEqual(self._count(), 1)

    def test_exception_rolls_the_whole_scope_back(self):
        with self.assertRaises(ValueError):
            with self.database.writing() as q:
                q.insert_latency(stage="a", track_id=None, ms=1.0, at=0.0)
                q.insert_latency(stage="b", track_id=None, ms=1.0, at=0.0)
                raise ValueError("boom")
        self.assertEqual(self._count(), 0)

    def test_nested_write_scopes_commit_once_at_the_outermost_exit(self):
        # A second thread reads on its own connection, so it sees only what has
        # actually been committed — unlike a nested scope on this thread, which
        # joins the open transaction and reads its own uncommitted writes.
        def committed_count():
            result = []
            t = threading.Thread(target=lambda: result.append(self._count()))
            t.start()
            t.join(10)
            return result[0]

        with self.database.writing() as q:
            q.insert_latency(stage="outer", track_id=None, ms=1.0, at=0.0)
            # A helper opening its own scope joins this one instead of
            # committing early or deadlocking on the write lock.
            self.database.catalog.record_latency("inner", None, 2.0, 0.0)
            self.assertEqual(self._count(), 2, "nested scope sees its own writes")
            self.assertEqual(committed_count(), 0, "committed before the outer exit")
        self.assertEqual(self._count(), 2)

    def test_a_failure_inside_a_nested_scope_rolls_back_the_outer_one(self):
        with self.assertRaises(ValueError):
            with self.database.writing() as q:
                q.insert_latency(stage="outer", track_id=None, ms=1.0, at=0.0)
                self.database.catalog.record_latency("inner", None, 2.0, 0.0)
                raise ValueError("boom")
        self.assertEqual(self._count(), 0)

    def test_write_inside_a_read_scope_is_refused(self):
        """Escalating would skip the write lock taken at scope entry."""
        with self.assertRaises(DatabaseError) as cm:
            with self.database.reading():
                self.database.catalog.record_latency("nope", None, 1.0, 0.0)
        self.assertIn("write scope inside a read scope", str(cm.exception))

    def test_save_ingested_track_is_atomic(self):
        row = {"id": "t1", "name": "N", "artist": "A", "genre": "house",
               "license": "CC BY 4.0", "nd": False, "sa": False, "nc": False,
               "mixable": True, "native_bpm": 124.0, "camelot": "8A",
               "duration_s": 60.0, "audio_path": "/x.wav",
               "analysis": {"bpm": 124.0}, "segments": [{"label": "intro"}]}
        self.database.catalog.save_ingested_track(
            row, [(124, 1.0, "/v124.wav", 60.0), (125, 1.008, "/v125.wav", 59.5)])
        with self.database.reading() as q:
            track = q.get_track(id="t1")
            self.assertTrue(track.mixable)                  # BOOLEAN round trip
            self.assertEqual(track.analysis_json, {"bpm": 124.0})   # JSONDOC
            self.assertEqual([v.grid_bpm for v in
                              q.list_variants_for_track(track_id="t1")], [124, 125])

    def test_reingesting_a_track_keeps_its_variants(self):
        """Upsert, not INSERT OR REPLACE: replace would delete the row and
        cascade its rendered variants away."""
        row = {"id": "t2", "name": "N", "artist": "A", "genre": "house",
               "license": "CC BY 4.0", "nd": False, "sa": False, "nc": False,
               "mixable": True, "native_bpm": 124.0, "camelot": "8A",
               "duration_s": 60.0, "audio_path": "/x.wav",
               "analysis": None, "segments": None}
        self.database.catalog.save_ingested_track(row, [(124, 1.0, "/v.wav", 60.0)])
        self.database.catalog.save_ingested_track(dict(row, name="Renamed"))
        with self.database.reading() as q:
            self.assertEqual(q.get_track(id="t2").name, "Renamed")
            self.assertEqual(len(q.list_variants_for_track(track_id="t2")), 1)


class TestConcurrency(unittest.TestCase):
    """The failure the previous layer was open to: one connection shared by
    every Flask worker thread, with a lock around only some of the writes."""

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="djdb_"))
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.database = Database.from_url(
            "sqlite:///" + str(self.tmp / "t.sqlite3")).migrate()
        self.addCleanup(self.database.dispose)

    def _run(self, target, n=8):
        errors = []

        def wrapper(i):
            try:
                target(i)
            except BaseException as exc:       # noqa: BLE001 - reported below
                errors.append(exc)

        threads = [threading.Thread(target=wrapper, args=(i,)) for i in range(n)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        return errors

    def test_concurrent_writers_all_land(self):
        writes_per_thread = 25

        def write(i):
            for j in range(writes_per_thread):
                self.database.catalog.record_latency("stage%d" % i, None, float(j), 0.0)

        self.assertEqual(self._run(write), [])
        with self.database.reading() as q:
            summary = {r.stage: r.n for r in q.latency_summary()}
        self.assertEqual(len(summary), 8)
        self.assertTrue(all(n == writes_per_thread for n in summary.values()),
                        summary)

    def test_readers_run_while_a_writer_holds_the_lock(self):
        """WAL: a reader must not block behind an in-flight write."""
        self.database.catalog.record_latency("seed", None, 1.0, 0.0)
        writer_in_scope = threading.Event()
        reader_done = threading.Event()

        def writer():
            with self.database.writing() as q:
                q.insert_latency(stage="slow", track_id=None, ms=1.0, at=0.0)
                writer_in_scope.set()
                self.assertTrue(reader_done.wait(5), "reader blocked on the writer")

        def reader():
            self.assertTrue(writer_in_scope.wait(5))
            with self.database.reading() as q:
                q.latency_summary()
            reader_done.set()

        threads = [threading.Thread(target=writer), threading.Thread(target=reader)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(10)
        self.assertTrue(reader_done.is_set())

    def test_each_thread_gets_its_own_connection(self):
        seen = {}
        lock = threading.Lock()

        def grab(i):
            with self.database.engine.connection() as conn:
                with lock:
                    seen[threading.get_ident()] = id(conn)

        self.assertEqual(self._run(grab), [])
        self.assertEqual(len(set(seen.values())), len(seen))

    def test_concurrent_upserts_of_one_track_converge(self):
        base = {"name": "N", "artist": "A", "genre": "house",
                "license": "CC BY 4.0", "nd": False, "sa": False, "nc": False,
                "mixable": True, "native_bpm": 124.0, "camelot": "8A",
                "duration_s": 60.0, "audio_path": "/x.wav",
                "analysis": None, "segments": None}

        def upsert(i):
            self.database.catalog.save_ingested_track(
                dict(base, id="same", name="writer%d" % i),
                [(124 + i, 1.0, "/v%d.wav" % i, 60.0)])

        self.assertEqual(self._run(upsert), [])
        with self.database.reading() as q:
            self.assertIsNotNone(q.get_track(id="same"))
            self.assertEqual(len(q.list_variants_for_track(track_id="same")), 8)


class TestFixtureCatalogReads(unittest.TestCase):
    """The generated bindings against the real ingested fixture catalog."""

    @classmethod
    def setUpClass(cls):
        cls.database, _, _ = get_fixture()

    def test_summaries_match_full_rows_without_the_blobs(self):
        with read() as q:
            full = {t.id: t for t in q.list_tracks()}
            summaries = q.list_track_summaries()
        self.assertEqual([s.id for s in summaries], sorted(full))
        for s in summaries:
            self.assertEqual((s.name, s.artist, s.mixable),
                             (full[s.id].name, full[s.id].artist, full[s.id].mixable))
            self.assertFalse(hasattr(s, "analysis_json"))

    def test_count_matches_the_listing(self):
        with read() as q:
            self.assertEqual(q.count_tracks(), len(q.list_tracks()))

    def test_grid_map_matches_per_track_queries(self):
        from backend.db.catalog import grid_bpms_by_track
        with read() as q:
            grids = grid_bpms_by_track(q)
            for track in q.list_tracks():
                per_track = [v.grid_bpm for v in
                             q.list_variants_for_track(track_id=track.id)]
                self.assertEqual(grids.get(track.id, []), per_track, track.id)

    def test_missing_rows_return_none_not_an_error(self):
        with read() as q:
            self.assertIsNone(q.get_track(id="nope"))
            self.assertIsNone(q.get_track_analysis(id="nope"))
            self.assertEqual(q.list_variants_for_track(track_id="nope"), [])


if __name__ == "__main__":
    unittest.main()
